### ISSUE TITLE
task: find out how downstreams detect a clean merge that is wrong, and how large that class is here

### ISSUE THREAD

**Issue by tucktuck101** [launchpad-26/buzz#363]
### Parent PRD

#273

### The question

**How do downstream forks detect an upstream change that merges cleanly and is nonetheless wrong for them — and how large is that class here?**

ADR-0022 adopts everything outside the contested surface unreviewed and states its own counter-example at full strength: upstream's `bin/.lefthookrc` sets `LEFTHOOK_BIN` to lefthook 2.1.3, the version ADR-0017 records as crashing every contributor's first push in this fork, because the branch name `launchpad` collides with the `launchpad/` directory. That file is not in the ledger, does not conflict, and merges clean. The record says plainly that the scope ruling does not solve this and should not be read as claiming it does.

**So the hole is acknowledged, and nothing is known about it.** Two things missing:

1. **How is this class found at all?** It is not a merge conflict, so no git mechanism sees it. Other downstreams hit this constantly — an upstream change that is fine upstream and breaks the downstream's local arrangement. There is practice here: integration test suites that encode the downstream's own invariants, canary or staged adoption, dependency-direction analysis, "our assumptions" checklists run against each import.
2. **How big is it here?** We know of exactly one instance, found by accident during an unrelated sweep. Nobody has looked for the second.

### Objective

A recorded answer describing how downstreams detect clean-merge-but-wrong adoptions, plus a first enumeration of which of this fork's 27 divergences have an assumption an uncontested upstream file could break.

### Why #273 cannot proceed without this

ADR-0022's affordability argument is that only the contested surface needs adjudication. That holds only if the uncontested remainder cannot hurt us in ways adjudication would have caught. One known instance already shows it can. #296 draws the boundary between mechanical resolution and escalation, and a boundary defined only over conflicts is blind to this class by construction — the record says so. Without knowing how the class is detected, the drop report specified in #306 has no way to surface it, and the fork's assurance against 788 unreviewed files reduces to `just ci`, which is itself in question at the CI-feasibility gap filed alongside this one.

### Definition of done

- [ ] At least three detection practices from other projects are described, with what each catches and what it misses.
- [ ] The fork's 27 divergences are walked for the pattern "this depends on an assumption about a file we do not own", and the ones that do are listed. `bin/lefthook` / lefthook 2.1.3 / branch-name collision is the known instance; the question is whether it is the only one.
- [ ] For each found, what an upstream change would have to do to break it is stated — so a future drop report has something to check against.
- [ ] Whether any detection practice is affordable at this fork's scale is judged honestly. "Nothing affordable exists and the risk is accepted" is a legitimate answer and is better than an unstated one.

### If we guess instead

We accept a stated hole without knowing its size. The fork reintroduces #196 on the next drop, having written down that it might, and having done nothing about it because nobody knew what could be done. If there are five more instances rather than one, ADR-0022's cost is materially different from what was accepted when it was recorded — and the record deserves to be revisited with that number rather than left standing on a sample of one.

### Impacted components

```
bin/lefthook
bin/.lefthookrc            (arrives from upstream)
lefthook.yml
launchpad/decisions/ADR-0017-lefthook-pin-upstream-boundary-exception.md
```

Bears on ADR-0022's accepted risk, #296 and #306.

### Out of scope

- Reopening ADR-0022. Curation scoped to the contested surface is decided; this measures a hole the record itself declares open.
- Fixing #196.
- Building any detection mechanism.
---

<sub>Filed by an AI agent (Claude Opus 5) on behalf of @tucktuck101 on 2026-08-22, as part of a knowledge-gap sweep over #273. This issue asks a question. It does not answer it, does not propose a decision and closes nothing — agents draft, humans decide (`launchpad/AGENTS.md` §5.1). Three headings beyond `02-task.yml` (**The question**, **Why #273 cannot proceed without this**, **If we guess instead**) are present because the sweep brief requires each gap to carry them.</sub>

**Comment by tucktuck101** [comment]
## Answer

**Nobody has solved this, and the research says nobody is close** — the best published tool detects **32%** of semantic conflicts, and its authors conclude *"developers cannot rely solely on such semantic merge tools for detecting conflicts."*

**Size here: 23 of the fork's 27 contested files are structurally exposed; 4 are not.** One instance demonstrated, one alleged instance refuted, and no further break pending in this drop.

Written up in **PR #405** → `launchpad/Research/363-detecting-clean-but-wrong-merges.md`.

---

### The fork's version of the class is narrower than the literature's

Most of what makes this class hard in research is invisible interference between two *feature* changes. This fork's version is an upstream restructuring that invalidates a fork *edit* — and two of its three shapes are mechanically checkable:

| Shape | Detectable by | Instance here |
|---|---|---|
| Fork edit references something upstream deleted | **Compiler / build** | **Demonstrated** — #360's `relay_url` |
| Fork edit anchors on structure upstream renamed | **Anchor-survival grep** | None pending — 16 anchors tested, all intact |
| Fork edit still applies but no longer means what it did | Tests, ~32% recall | Unknown, and unknowable cheaply |

The first two are cheap pre-flights the fork does not run today.

### The measured state of the art

From [*Detecting Semantic Conflicts with Unit Tests*](https://arxiv.org/html/2310.02395) — 85 change pairs across 51 merge scenarios, testing SAM (four test generators against Base/Left/Right/Merge):

- **9 of 28 conflicts detected — recall 0.32**, precision 0.84
- 19 false negatives; 13 judged theoretically reachable with better generation
- Authors: *"developers cannot rely solely on such semantic merge tools for detecting conflicts"*

Its definition, for the record: *"two contributions … semantically conflict … when the specifications they are individually supposed to satisfy are not jointly satisfied by the program that integrates them."*

Electron, running one of the largest downstream patch sets in existence, treats it as a fact of life rather than a solved problem: *"When upstream code changes, patches can break—sometimes without even a patch conflict or a compilation error."*

**Anyone proposing a mechanism for #273 that claims to close this hole is overclaiming.**

### What actually works, ranked

1. **Build the merge.** Catches the whole first shape. #360 found `relay_url` this way; `merge-tree` — which every figure in the #273 thread rests on — could not have.
2. **Run the fork's own tests.** The literature's technique minus the automation: tests encoding *the fork's* invariants. The fork already has one — `scripts/test-ci-changed-paths-filter.sh`, a contract test for a fork divergence. Exactly the right pattern.
3. **Assert the position survived** (#362) — cheap, arbitrary, cannot fail silently.
4. Generated-test tooling — 32% recall, Java-only tools. Not worth it here.
5. Staged/canary adoption — standard in distributions, needs somewhere to stage.

### Sizing it here: coupling follows the *form* of the divergence

A fenced append cannot be invalidated by upstream restructuring. An in-place edit can, by construction.

| Form | Count | Coupled? |
|---|---|---|
| Fenced append-only block (`AGENTS.md`) | 1 | **No** |
| Whole-file replacement (`config.yml`) | 1 | **No** |
| Deletion (2 legacy templates) | 2 | **No** |
| **In-place edit** | **23** | **Yes, by construction** |

**`AGENTS.md` is the empirical proof of the distinction.** It is one of the 8 files both sides touched, and it **auto-merged cleanly in both of the fork's drops** (#12 and #216) because the fork's change is a delimited append with `<!-- launchpad-26 fork: begin/end -->` markers.

### Anchor-survival: nothing else pending

```
  lefthook.yml branch-skew lane                  anchor PRESENT (1)
  Justfile SIDECARS array                        anchor PRESENT (3)
  ci.yml desktop paths-filter group              anchor PRESENT (3)
  dev-setup.sh redis guard fn                    anchor PRESENT (2)
  instance-env.sh BUZZ_RELAY_PORT                anchor PRESENT (2)
  compose.yml BUZZ_IMAGE var                     anchor PRESENT (1)
  runtime.rs persona_drift_state                 anchor PRESENT (1)
  restore.rs spawn_agent_child call              anchor PRESENT (1)
  ... 16 checked, all intact
```

**But note what this does not catch.** #360's `relay_url` defect was *not* an anchor disappearance — `spawn_agent_child(` is present in the table above. Upstream deleted a *local binding* used 28 lines away. Anchor survival is necessary and not sufficient; claiming otherwise would be the exact false assurance this is about.

### The two instances on the record

**Demonstrated:** `relay_url`. Clean merge, compile failure, **and the resolution that compiles — upstream's own `&key.relay_url` — silently reintroduces the fork's bug** because `ManagedAgentRuntimeKey::new` normalises. That is the archetype: not merely clean-but-broken, but clean-but-broken with a plausible wrong fix.

**Refuted:** `bin/.lefthookrc`. It does not pin 2.1.3 — it resolves `bin/lefthook`, which the fork points at 2.1.10, and upstream never touched the symlink. Tested in the merged tree: reports `2.1.10`. Protective, not hazardous; only the comment mentions 2.1.3.

**So the fork's risk register contains one item that is not real and omits the one that is.**

### What this changes for #273

**ADR-0022's declared hole is real and its size is 23 rows, not 1 file.** What changes is the example — `.lefthookrc` should be replaced with `relay_url`.

**Two cheap pre-flights fall out, neither needing a decision:** build the merge before proposing it (highest-value change available, already how #216 was done by hand); and an anchor-survival grep per ledger row — which requires the ledger to record *what upstream structure each row depends on*, a column #294 lacks and the natural companion to #361's `Upstream-Status`.

**#296 should not adopt "a build passes" as its boundary** — `relay_url` is the counter-example.

**#307 has its empirical argument, and it is cheaper than #307 frames it.** A fenced append survived both drops untouched. A fence *inside* a shared file is enough; a separate file is not required.

### Confidence, and what is still unknown

**High** on the research figures (verbatim, including the authors' conclusion) and on the anchor-survival results and form classification (reproducible).

**The 23-of-27 count is structural, not probabilistic.** It means 23 *can* be invalidated. Nothing in the literature gives a per-import rate, and two drops is not a sample, so I have not estimated likelihood.

**Not checked.** The anchor patterns are my own choice of what each edit depends on; a different reading could reach a different count. I checked 16 dependencies, not all 23. **I did not attempt to detect any third-shape conflict** — that residue is unmeasured and, at this cost, unmeasurable. I did not run the fork's test suites (disk exhaustion, per #360), so my own detection was compilation only. I read one of three surfaced papers.

**Sources:** [Detecting Semantic Conflicts with Unit Tests](https://arxiv.org/html/2310.02395) · [ScienceDirect version](https://www.sciencedirect.com/science/article/pii/S0164121224001158) · [Patches in Electron](https://www.electronjs.org/docs/latest/development/patches) · [Using PLMs to Resolve Textual and Semantic Merge Conflicts](https://www.microsoft.com/en-us/research/wp-content/uploads/2022/07/issta22-merge-conflicts-llm.pdf)

---

<sub>Answered by an AI agent (Claude Opus 5) on behalf of @tucktuck101 on 2026-08-22. Read-only: `git show` / `grep` for the anchor test, plus published research. The only repository write is one research document on branch `research/363-clean-merge-wrong`, offered as PR #405 and not merged. Nothing closed, nothing decided.</sub>
