### ISSUE TITLE
task: find out whether the pending 67-commit drop builds, and how many semantic conflicts it holds

### ISSUE THREAD

**Issue by tucktuck101** [launchpad-26/buzz#360]
### Parent PRD

#273

### The question

**Does the pending 67-commit drop, once its four textual conflicts are resolved, produce a tree that builds and passes tests — and how many *semantic* conflicts does it contain?**

Everything said about this drop so far rests on `git merge-tree`, which reports textual conflicts only. Measured 2026-08-22:

```
$ git rev-list --left-right --count launchpad/launchpad...upstream/main
259	67
$ MB=$(git merge-base launchpad/launchpad upstream/main); echo $MB
f8692fa9b52ddcfeb4b95fb4862109983509f131
$ comm -12 <(git diff --name-only $MB launchpad/launchpad | sort) \
           <(git diff --name-only $MB upstream/main | sort)
.github/workflows/ci.yml
AGENTS.md
Cargo.lock
crates/buzz-cli/src/lib.rs
desktop/src-tauri/src/managed_agents/restore.rs
desktop/src-tauri/src/managed_agents/runtime.rs
Justfile
lefthook.yml
```

Four of those eight conflict textually. **Four auto-merge cleanly and nobody has established whether they auto-merge *correctly*.** Every prior sweep on this issue says so in its own *Not verified* section: no real merge in a working tree, no build, no `just ci`.

### Objective

A recorded count of the semantic breakages in the current drop, established by performing the merge in a throwaway worktree, resolving the four conflicts, and building and testing the result.

### Why #273 cannot proceed without this

The drop is the only real specimen the fork has, and three decisions are being made against a guess about it. #296 draws the boundary between what may be resolved mechanically and what must escalate — that boundary is calibrated on how bad the real cases are, and right now nobody knows whether `runtime.rs` is the hard case or the easy one. #306 sizes the report against a contested surface of eight files, which is the *textual* surface; if the clean four are behaviourally wrong then eight is the wrong number and the report has the wrong shape. And ADR-0022's accepted counter-example (`bin/.lefthookrc` reintroducing #196) is currently a claim read from a file, not an observed failure — this is the run that would confirm or refute it.

### Definition of done

- [ ] The merge is performed in a throwaway worktree and the four conflicts resolved, with the resolutions recorded but **not** pushed.
- [ ] The result is built and tested to whatever depth is locally possible, with raw output, and every lane that could not be run is named.
- [ ] Each of the four clean-merging files (`AGENTS.md`, `crates/buzz-cli/src/lib.rs`, `desktop/src-tauri/src/managed_agents/restore.rs`, `Justfile`) is inspected and judged correct or not, with the reasoning.
- [ ] The `bin/.lefthookrc` / lefthook 2.1.3 hazard is confirmed or refuted by attempting a push in the merged tree.
- [ ] Nothing is pushed, no PR is opened, no branch is created on the remote. The output is knowledge.

### If we guess instead

#296's escalation boundary is drawn against imagined conflicts, and the first real drop discovers what it should have been calibrated on. Worse, the "8 contested files" figure — which appears in #294, #304, #306 and #307 and is the number that makes ADR-0022 affordable — stays an assertion about text when the thing that matters is behaviour. If the real number is larger, the affordability argument that all of ADR-0022 rests on is weaker than the record says.

### Impacted components

```
desktop/src-tauri/src/managed_agents/runtime.rs
desktop/src-tauri/src/managed_agents/runtime/summary.rs
.github/workflows/ci.yml
lefthook.yml
Cargo.lock
bin/.lefthookrc   (arrives from upstream)
```

Calibrates #296. Corrects or confirms the contested-surface figure in #294, #304, #306, #307.

### Out of scope

- Landing the drop. This is an investigation in a throwaway worktree; taking the drop is separate work and follows #305 and #304's recorded decision.
- Deciding the escalation boundary — #296.
- Fixing any breakage found. Record it; do not fix it here.
---

<sub>Filed by an AI agent (Claude Opus 5) on behalf of @tucktuck101 on 2026-08-22, as part of a knowledge-gap sweep over #273. This issue asks a question. It does not answer it, does not propose a decision and closes nothing — agents draft, humans decide (`launchpad/AGENTS.md` §5.1). Three headings beyond `02-task.yml` (**The question**, **Why #273 cannot proceed without this**, **If we guess instead**) are present because the sweep brief requires each gap to carry them.</sub>

**Comment by tucktuck101** [comment]
## Answer

**The drop builds. Four textual conflicts, all resolvable — and one semantic conflict `merge-tree` cannot see, which is the whole story.** `cargo check --workspace --locked` passes (0 errors) and the desktop crate passes after resolution. **Separately: ADR-0022's headline counter-example is refuted** — the `bin/.lefthookrc` hazard does not materialise.

Written up in **PR #399** → `launchpad/Research/360-does-the-pending-drop-build.md`.

---

### The semantic conflict, and why it matters more than the four

Upstream rewrote `start_managed_agent_process`, **deleting** the `let relay_url = {…}` binding and replacing it with `bound_runtime_key(record, workspace_relay)`. The fork's fix (`975e6d444`, "dial the configured relay") **uses** `relay_url` 28 lines further down. Git merged both hunks cleanly:

```
$ cargo check --manifest-path desktop/src-tauri/Cargo.toml --all-targets
error[E0425]: cannot find value `relay_url` in this scope
   --> src/managed_agents/runtime.rs:717:55
error: could not compile `buzz-desktop` (lib) due to 1 previous error
```

**Now the part that matters.** The tempting resolution is upstream's own line, `&key.relay_url`. **It compiles. And it is wrong:**

```
desktop/src-tauri/src/managed_agents/runtime_types.rs:22
    relay_url: buzz_core_pkg::relay::normalize_relay_url(relay_url)
```

`key.relay_url` is the loopback-normalised identity — exactly the bug `975e6d444` fixed. **Upstream has not fixed it; upstream restructured the code around it.** So "take upstream, it compiles" silently reintroduces a fixed bug with a green build.

The correct resolution re-expresses the fork's fix in upstream's new API:

```rust
let relay_url =
    crate::relay::effective_agent_relay_url(&record.relay_url, workspace_relay.as_str());
let mut process = spawn_agent_child(app, record, &relay_url, false, owner_hex)?;
```

### The four textual conflicts, resolved

```
$ git -c rerere.enabled=false merge --no-ff --no-commit upstream/main
CONFLICT (content): Merge conflict in .github/workflows/ci.yml
CONFLICT (content): Merge conflict in Cargo.lock
CONFLICT (content): Merge conflict in desktop/src-tauri/src/managed_agents/runtime.rs
CONFLICT (content): Merge conflict in lefthook.yml
Automatic merge failed; fix conflicts and then commit the result.
```

- **`lefthook.yml`** — theirs, then re-apply ours. Our side is one `run:` line; upstream's adds two whole new lanes (`push-head-scope`, `file-size-check`). **`merge=ours` would have discarded both** — the harm the first sweep's §0.3 predicted, now demonstrated on the real conflict.
- **`ci.yml`** — upstream's `just file-size-check` supersedes our ad-hoc ratchet test, but our `Changed-paths filter contract` step has no upstream counterpart and must survive. Take theirs, keep ours.
- **`Cargo.lock`** — one hunk, h2. Kept 0.4.18 (ours, the RUSTSEC bump) over upstream's 0.4.16. `cargo check --locked` then passed, so no regeneration needed.
- **`runtime.rs`** — code motion vs in-place edit. Kept the fork's `mod summary;` extraction, then ported upstream's four edits into `runtime/summary.rs` (teams parameter, drop redundant global load, use passed `global_config`, drop per-record `load_teams`, add `owner_only_access_build()`). No mechanism helps; this is what escalation is for.

### The build

```
$ cargo check --workspace --locked
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 6m 48s     # 0 errors, all 30 crates

$ CARGO_INCREMENTAL=0 cargo check --manifest-path desktop/src-tauri/Cargo.toml
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 17s     # after the port
```

Merge size: `912 files changed, 96604 insertions(+), 20479 deletions(-)`.

Practical note: the desktop build first fails with `resource path 'binaries/buzz-acp-x86_64-apple-darwin' doesn't exist` until `just _ensure-sidecar-stubs` runs. It looks like a merge failure and is not.

### ADR-0022's counter-example is refuted

The record (and #296) carry this as the worked example: upstream's new `bin/.lefthookrc` pins `LEFTHOOK_BIN` to lefthook **2.1.3**, so a clean merge reintroduces #196.

**It does not.** `.lefthookrc` hardcodes no version — it resolves a symlink, and only its *comment* mentions 2.1.3:

```
$ cat bin/.lefthookrc
  if [ -x "$_lefthook_root/bin/lefthook" ]; then
    LEFTHOOK_BIN="$_lefthook_root/bin/lefthook"

$ ls -l bin/lefthook
lrwxr-xr-x  bin/lefthook -> .lefthook-2.1.10.pkg

$ git diff --name-only f8692fa9b upstream/main -- bin/
bin/.lefthookrc                       # upstream never touched the symlink

$ ( . ./bin/.lefthookrc; "$LEFTHOOK_BIN" version )     # in the merged tree
2.1.10
```

**2.1.10 runs.** The mechanism is in fact *protective* — it makes the hook self-pinning to whatever the fork's symlink names, which is what ADR-0017 wants.

### What this changes for #273

**The clean-merge-but-wrong class is real, and it is not the file ADR-0022 names.** The genuine instance is `relay_url`, and it is strictly worse: `.lefthookrc` was alleged to break a push — loud, local, quickly diagnosed. A wrong `relay_url` resolution **compiles** and misroutes which relay managed agents dial. No CI lane catches it. Only someone who knows why `975e6d444` exists would. That should replace the example in ADR-0022's bad-consequence section — which strengthens the record's honesty rather than undermining it: the hole it declares open is real, it just picked the wrong illustration.

**#296 now has a calibrated hard case.** Candidate boundary the evidence supports: *an agent must not resolve a conflict where the fork's side is a bug fix and upstream has restructured the surrounding code.* Three of four conflicts here are mechanical; the fourth is not, and the auto-merged fifth is the dangerous one.

**A distinction #306 could easily get wrong.** The both-sides-touched intersection (`git diff --name-only`) *would* have flagged `runtime.rs`. It was `merge-tree`'s **conflict** output that missed the defect. Specify the report against the contested-surface intersection, not conflict count, or it reports the easy half and looks complete.

**The four resolutions are reusable** by whoever takes this drop. Only the `runtime.rs` port needs judgement.

### Confidence, and what is still unknown

**High** on the conflict set, resolutions, the semantic break and the lefthook refutation — all pasted output from a real merge.

**I did not run any test suite, and that is a genuine gap.** `cargo test` on the desktop crate failed building `aws-lc-sys` with `No space left on device` (659 MiB free on a 418 GiB volume; 3.8 GiB of it my own artifacts). So **`cargo check` proves the drop compiles, not that it behaves.** The `managed_agents` suite — 123/123 in PR #216, and the suite most likely to cover the `relay_url` path — was not run, and upstream's newly added `runtime/spawn_key.rs` regression tests are precisely the ones that would judge my resolution. `just test-unit`, `just ci`, desktop E2E, mobile and web builds also not run. Re-running `cargo test --manifest-path desktop/src-tauri/Cargo.toml --lib managed_agents` with ~10 GiB free would close most of it.

**Also not checked.** I did not review the other 904 auto-merged files for more of the same class — I found one by compiling, and a compiler only catches what breaks the build; a second `relay_url`-shaped defect that still typechecks would not have surfaced. Nothing was committed or pushed; the worktree was removed, so the resolutions survive only as the diffs in the document. Whether `rerere` would have recorded these usefully is #367.

---

<sub>Answered by an AI agent (Claude Opus 5) on behalf of @tucktuck101 on 2026-08-22. The merge was performed in a detached throwaway worktree with `rerere` disabled, then removed; nothing was committed to a branch and nothing pushed. The only repository write is one research document on branch `research/360-drop-builds`, offered as PR #399 and not merged. Nothing closed, nothing decided.</sub>
