### ISSUE TITLE
bug: build note is titled for a 67-commit drop but merged an unpinned 912-file one

### ISSUE THREAD

**Issue by serina-mcfall** [launchpad-26/buzz#423]
### Observed behaviour

`launchpad/Research/360-does-the-pending-drop-build.md` is titled and framed around "the pending 67-commit drop", and its parent issue #360 measured that scope. But its own header table reports:

> Merge size: **912 files**, +96,604/−20,479

912 files is not the 67-commit scope. At the 67-commit point:

```
$ c67=$(git rev-list f8692fa9b..upstream/main | tail -67 | head -1)   # 9891e64f6, 2026-08-21 07:07
$ git diff --name-only f8692fa9b $c67 | wc -l
796
```

796 files. 912 is close to today's tip. The document ran `git merge --no-ff --no-commit upstream/main` — against the **moving ref**, not the pinned point its title describes — and never records which SHA of `upstream/main` it actually merged.

So the build was performed against a larger, later, unidentified drop than the one the document is named for.

### Expected behaviour

Record the tip at merge time and reconcile the framing:

```
TIP=$(git rev-parse upstream/main)
echo "merged f8692fa9b..$TIP"
```

Then either retitle to the scope actually tested, or re-run at the pinned 67-commit point. Cross-reference issue #384, which tracks this same unpinned-tip pattern across research notes.

### Reproduction

Compare the document's title and its header table's file count, then run the command above.

### Environment

`launchpad-26/buzz`, PR #399's added file `launchpad/Research/360-does-the-pending-drop-build.md`. Checked 2026-08-22.

### Impacted components

- `launchpad/Research/360-does-the-pending-drop-build.md` — the header table and the "67-commit" framing
- `launchpad/Research/362-...` / #403's confidence section, which references "the real 912-file drop" from the same run — same gap, one fix

### What this does not undermine

The document's specific findings survive, because the files they name are common to both scopes and I checked them independently:

- The build claim is a **real build**, not an inference from `git merge-tree`: `cargo check --workspace --locked` finishing in 6m48s, then a genuine `error[E0425]: cannot find value 'relay_url' in this scope --> src/managed_agents/runtime.rs:717:55`, then a clean pass after the fix. The document also states plainly that it did not run `cargo test` or `just ci` (disk exhaustion), so "compiles" is not inflated into "behaves".
- The semantic conflict is **named and located**, not asserted in the abstract: `runtime.rs:717`, commit `975e6d444`, and `runtime_types.rs:22`'s `normalize_relay_url` call. Verified: that commit exists and touches exactly those files, and that line does contain the call.
- The `bin/.lefthookrc` refutation is verified — it resolves `bin/lefthook` rather than hardcoding 2.1.3, and the symlink points at `.lefthook-2.1.10.pkg`.

**Not a blocker.** The findings hold; the framing describes a different drop than the one tested.

Filed from the review of #399.

**Comment by tucktuck101** [comment]
Descoped 2026-08-24 — does not serve the six 18-Sep deliverables. See buzz-infrastructure/project-management/2026-08-24-rescope.md.
